@startuml
class CollisionDetector {
}
class CollisionEvent {
}
class "UnityEvent`1"<T> {
}
MonoBehaviour <|-- CollisionDetector
CollisionDetector +-- CollisionEvent
"UnityEvent`1" "<Collision2D>" <|-- CollisionEvent
@enduml
