@startuml
class EatableObjSO {
    + Name : string
    + InitSize : float
    + isPlayer : bool = false
    + Size : float <<get>> <<set>>
    + Init() : void
}
ScriptableObject <|-- EatableObjSO
EatableObjSO --> "m_Sprite" Sprite
@enduml
