@startuml
class Timer {
    + StartTime : int <<get>>
    + Time : float <<get>>
    + IsTimeOver : bool <<get>>
    OnEnable() : void
    + Update() : void
    + Reset() : void
}
ScriptableObject <|-- Timer
Timer --> "gameSetting" GameSetting
@enduml
