@startuml
class EatableObjContoroller {
    Start() : void
    + ObjSize : float <<get>>
    - OnDestroy() : void
}
MonoBehaviour <|-- EatableObjContoroller
IEatable <|-- EatableObjContoroller
EatableObjContoroller --> "objSO" EatableObjSO
EatableObjContoroller --> "UIEaten" UIEatenView
EatableObjContoroller --> "m_Renderer" Renderer
@enduml
