@startuml
class PlayerController {
    DistancePlayerScale : float
    Distance : float
    Update() : void
    + AwayCamera() : void
}
MonoBehaviour <|-- PlayerController
PlayerController --> "PlayerSO" EatableObjSO
PlayerController --> "targetGroup" CinemachineTargetGroup
@enduml
