@startuml
namespace Director{
class GameDirector {
    + GoalSize : float <<get>>
    + Awake() : void
    + DestroySelf() : void
}
MonoBehaviour <|-- GameDirector
GameDirector --> "gameSetting" GameSetting
GameDirector --> "timer" Timer
GameDirector --> "Instance" GameDirector
note left of GameDirector : シングルトンパターン
}
@enduml
