@startuml
!include .\\GameDirector.puml
!include .\\UIs\Buttons.puml
!include .\\UIs\GameOverSceneManager.puml
!include .\\UIs\GameOverSceneUnload.puml
!include .\\UIs\PlayerCameraController.puml
!include .\\UIs\TimerEvent.puml
!include .\\UIs\TitleSceneManager.puml
!include .\\UIs\UIEatenView.puml
!include .\\UIs\UISizeManager.puml
!include .\\UIs\UITimerControl.puml
!include .\\UIs\UI_TimeManager.puml
!include .\\UIs\VCamFollow.puml
@enduml
