@startuml
class EatableObjContoroller {
    - Ratio : float = 10
    - PlayerSize : float
    - ObjSize : float
    Start() : void
    + Eaten() : void
    + IsEatable() : bool
}
MonoBehaviour <|-- EatableObjContoroller
IEatable <|-- EatableObjContoroller
EatableObjContoroller --> "Player" SpriteRenderer
EatableObjContoroller --> "Renderer" SpriteRenderer
@enduml
