@startuml
class TitleSceneManager {
    FadeTime : float = 1
    CharEatWaitTime : float = 0.5f
    MoveDistance : float = 0.58f
    Increment : float = 0.1f
    Update() : void
    CharEat() : IEnumerator
    MoveEater() : IEnumerator
}
MonoBehaviour <|-- TitleSceneManager
TitleSceneManager --> "StartText" Text
TitleSceneManager --> "EatPlayer" Transform
@enduml
