@startuml
class UI_TimeManager {
    time : float
    Update() : void
    + OnGameOver() : void
}
MonoBehaviour <|-- UI_TimeManager
UI_TimeManager --> "FinishUI" GameObject
UI_TimeManager --> "ease" Ease
@enduml
